version: "3.4"
services:
  front:
    build:
      context: ./front/mainfront
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
  frontsso:
    build:
      context: ./front/frontsso
    ports:
      - "3001:3000"
    stdin_open: true
    tty: true
  apicommands:
    image: mcr.microsoft.com/dotnet/core/aspnet:latest
    build:
      context: ./path_to_your_api_project
      dockerfile: front/mainfront/Dockerfile
    ports:
      - "4000:5000"
  apiuser:
    image: mcr.microsoft.com/dotnet/core/aspnet
    ports:
      - "4001:5000"
    expose:
      - "4003"
  dbuser:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: dbuser
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
    ports:
      - "5000:5432"
  dbcommands:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: dbcommands
      POSTGRES_USER: command
      POSTGRES_PASSWORD: command
    ports:
      - "5001:5432"
  busmailer:
    image: rabbitmq:3-management
    ports:
      - "6000:5672"
    expose:
      - "4004"
  mailer:
    image: catatnight/postfix
    ports:
      - "6001:587"
    expose:
      - "4014"
