version: "3.4"
services:
  front:
    build:
      context: ./front/mainfront
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
  frontsso:
    build:
      context: ./front/frontsso
      dockerfile: ./Dockerfile
    ports:
      - "3001:3000"
    stdin_open: true
    tty: true
  dbuser:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: dbuser
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
    ports:
      - "5007:5432"
  dbcommands:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: dbcommands
      POSTGRES_USER: command
      POSTGRES_PASSWORD: command
    ports:
      - "5432:5432"
    volumes:
      - ./back/data:/var/lib/postresql/data
  apicommands:
    build:
      context: ./back/api/command-microservices
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - "dbcommands"
  apiuser:
    build:
      context: ./back/api/user-microservices
      dockerfile: Dockerfile
    ports:
      - "4001:5000"
  busmailer:
    image: rabbitmq:3-management
    ports:
      - "6000:5672"
    expose:
      - "4004"
  mailer:
    image: catatnight/postfix
    ports:
      - "6001:587"
    expose:
      - "4014"
volumes:
  pgdata: