version: '3.4'
services:
  front:
    build: ./front
    ports:
      - '3001:3001'
    stdin_open: true
    tty: true
  frontSSO:
    image: node:lts
    ports:
      - '3002:3002'
    expose:
      - '3002'
  apicommands:
    image: mcr.microsoft.com/dotnet/core/aspnet:latest
    build:
      context: ./path_to_your_api_project
      dockerfile: Dockerfile
    ports:
      - "4001:4001"
  apiuser:
    image: mcr.microsoft.com/dotnet/core/aspnet
    ports:
      - '4003:4003'
    expose:
      - '4003'
  dbuser:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: dbuser
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
    ports:
      - "5002:5002"
  dbcommands:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: dbcommands
      POSTGRES_USER: command
      POSTGRES_PASSWORD: command
    ports:
      - "5001:5001"
  busmailer:
    image: rabbitmq:3-management
    ports :
      - '4004:4004'
    expose:
    - '4004'
  mailer:
    image: catatnight/postfix
    ports :
      - '4014:4014'
    expose:
      - '4014'

networks:
  my_network:
    driver: bridge
