// <auto-generated />
using System;
using System.Numerics;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using command_microservices;

#nullable disable

namespace command_microservices.Migrations
{
    [DbContext(typeof(CommandDbContext))]
    [Migration("20231117174631_initial2")]
    partial class initial2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("command_microservices.Command", b =>
                {
                    b.Property<BigInteger>("ID")
                        .HasColumnType("numeric");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("TotalPrice")
                        .HasColumnType("integer");

                    b.Property<BigInteger>("UserID")
                        .HasColumnType("numeric");

                    b.HasKey("ID");

                    b.ToTable("Commands");
                });
#pragma warning restore 612, 618
        }
    }
}
